### ISSUE TITLE
apk?

### ISSUE THREAD

**Issue by ghost** [aleksey-saenko/TTLChanger#1]
could you provide us an apk? also consider publishing it on f-droid

**Comment by aleksey-saenko** [comment]
I submitted a [merge request](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13558) to the f-droid repository, but it hasn't moved for a month. Apparently the team doesn't have enough time to review the app.
I planned to upload the version signed by f-droid after publication or publish a link. But if you need it now, then I can publish a version signed with my own key. However, after publication, the app will be signed with a different key (you will need to reinstall the app to receive updates).

**Comment by aleksey-saenko** [comment]
@cyberhardt 
Check the releases section, I've added an apk for v1.1.1.

**Comment by aleksey-saenko** [comment]
The app was published on f-droid, you can find the link in the readme.
