### ISSUE TITLE
WRITE: Failure sysctl xwrite: invalid argument 

### ISSUE THREAD

**Issue by spiral009** [aleksey-saenko/TTLChanger#2]
Android 13 custom rom

**Comment by spiral009** [comment]
Enablin ipv6 options then hitting write will cause my phone to reboot after a while
Something start running in the background cause the phone to reboot i guess

**Comment by aleksey-saenko** [comment]
@ulist 
The app doesn't perform any actions in the background, except for applying the saved value on boot if the auto-start option is enabled. When performing writing and reading operations, single operations are executed.
Does the error "Failure sysctl xwrite: invalid argument" appear only when the IPv6 option is enabled? Does IPv4 work correctly?

**Comment by spiral009** [comment]
When Ipv6 option is disabled i get this error if i enable it and click on write phone runs slow and reboota

**Comment by spiral009** [comment]
What's option gets executed when ipv6 option is enabled?

**Comment by aleksey-saenko** [comment]
@ulist 
The app finds all IPv6 interfaces and writes its custom hop_limit [[sources](https://github.com/aleksey-saenko/TTLChanger/blob/master/app/src/main/java/com/mrsep/ttlchanger/data/TtlManagerImpl.kt)]:
```
for INTERFACE in $(sysctl -a 2>/dev/null | grep -Eo "^net\.ipv6\.conf\.[^\.]+\.hop_limit"); do sysctl -w $INTERFACE=%d; done
```
The app uses _sysctl_ utility to modifie the attributes of the kernel, but it varies across different OS.
Are you able to connect to your phone using ADB? It would be great if you could provide more information about how sysctl works on your custom rom.
To do this, follow these steps:
1. Enable "**USB debugging**" and "**Rooted debugging**" in "**Developer options**" on your phone temporarily.
2. Connect your phone to your PC.
3. Open the command line or terminal on your PC.
4. Run the following commands:
```
adb shell su
sysctl -w net.ipv4.ip_default_ttl=65 
```
if you get the same error try without key "-w":
```
sysctl net.ipv4.ip_default_ttl=65
```
Please let me know the results.

**Comment by spiral009** [comment]
What the hell
https://github.com/aleksey-saenko/TTLChanger/assets/39057208/e1384fb8-3b2e-49a2-aa68-d3d356f3e57d

**Comment by spiral009** [comment]
Is the issue is running 'sysctl -a' eats the memory and cause Device to crash

**Comment by aleksey-saenko** [comment]
Definitely, yes. It should display all values correctly. In my case, it works instantly without any freezes.

**Comment by spiral009** [comment]
See the memory dropped to 15M and phone start lags 

https://github.com/aleksey-saenko/TTLChanger/assets/39057208/2b87ac05-610a-4d0b-bba9-b195ac82b2b5

Any idea why is that happening?

**Comment by aleksey-saenko** [comment]
I would suggest trying to execute sysctl via ADB to eliminate additional errors/delays/memory leaks caused by the terminal app on the phone.
